on:
    push:
        branches:
          - master
    workflow_dispatch:

# 同じワークフローが進行中の場合、それを取り消す
concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true

jobs:
    build:
        timeout-minutes: 5
        permissions:
            contents: read
        runs-on: ubuntu-22.04
        continue-on-error: true
        steps:
            - uses: actions/checkout@v3

            - name: '*.html ファイルが存在しなければ、ビルド・デプロイは行わない'
              id: judge-whether-to-build
              uses: andstor/file-existence-action@20b4d2e596410855db8f9ca21e96fbe18e12930b # v2.0.0
              with:
                files: ./docs/**/*.html
                fail: true

            - uses: actions/setup-node@v3
              with:
                node-version: '18'

            # https://docs.github.com/ja/actions/using-workflows/caching-dependencies-to-speed-up-workflows#example-using-the-cache-action
            - name: Cache node modules
              id: cache-npm
              uses: actions/cache@v3
              env:
                cache-name: cache-node-modules
              with:
                # npm cache files are stored in `~/.npm` on Linux/macOS
                path: ~/.npm
                key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                    ${{ runner.os }}-build-${{ env.cache-name }}-
                    ${{ runner.os }}-build-
                    ${{ runner.os }}-

            - if: ${{ steps.cache-npm.outputs.cache-hit == 'false' }}
              name: List the state of node modules
              continue-on-error: true
              run: npm list

            - run: npm ci
            - run: npm run build

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v1
              with:
                path: ./docs

            - id: result
              run: echo "success=true" >> "$GITHUB_OUTPUT"

        outputs:
            whether-to-build: ${{ steps.judge-whether-to-build.outputs.files_exists }}
            success: ${{ steps.result.outputs.success }}

    deploy:
        needs: build
        if: ${{ needs.build.outputs.whether-to-build == 'true' }}

        timeout-minutes: 2
        permissions:
            pages: write
            id-token: write
        runs-on: ubuntu-22.04
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: buildでエラーが起こった場合にエラー
              if: ${{ needs.build.outputs.success != 'true' }}
              run: exit 1

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2
